const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const isMapPage=!!$('#canvas');
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const safe=t=>String(t??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)??JSON.stringify(f))}catch{return f}};
function theme(){document.body.classList.toggle('night');localStorage.setItem('oydin-theme',document.body.classList.contains('night')?'night':'light')}
$('#themeToggle')?.addEventListener('click',theme);if(localStorage.getItem('oydin-theme')==='night')document.body.classList.add('night');
if(!isMapPage)$('#learnMore')?.addEventListener('click',()=>$('#about')?.scrollIntoView({behavior:'smooth'}));
if(isMapPage){
const canvas=$('#canvas'),workspace=$('#workspace'),layer=$('#connections');
let mapId=localStorage.getItem('oydin-active-map')||'map-default';let maps=load('oydin-maps',{});if(!maps[mapId])maps[mapId]={id:mapId,title:'Yangi makon',cards:[],connections:[],space:'paper',updatedAt:new Date().toISOString()};
let current=maps[mapId],cards=current.cards||[],connections=current.connections||[];let selectedType='G‘oya',editingId=null,detailId=null,childParentId=null,connectingFrom=null,selectedConnection=null,zoom=100;
const spaces={paper:{name:'Sokin qog‘oz',class:'space-paper'},mist:{name:'Yumshoq tuman',class:'space-mist'},sand:{name:'Iliq qum',class:'space-sand'},night:{name:'Sokin tun',class:'space-night'},ink:{name:'Siyoh makon',class:'space-ink'}};
function persist(){current.cards=cards;current.connections=connections;current.title=$('#mapTitle').value.trim()||'Yangi makon';current.space=workspace.dataset.space||'paper';current.updatedAt=new Date().toISOString();maps[mapId]=current;localStorage.setItem('oydin-maps',JSON.stringify(maps));localStorage.setItem('oydin-active-map',mapId)}
function loadCurrent(){current=maps[mapId];cards=current.cards||[];connections=current.connections||[];$('#mapTitle').value=current.title||'Yangi makon';setSpace(current.space||'paper',false);render();requestAnimationFrame(drawConnections)}
function kindClass(t){return ({'G‘oya':'idea','Reja':'plan','Savol':'question','Kontekst':'context'})[t]||'idea'}
function cardCenter(c){const el=canvas.querySelector(`[data-id="${CSS.escape(String(c.id))}"]`);return el?{x:c.x+el.offsetWidth/2,y:c.y+el.offsetHeight/2}:{x:c.x+125,y:c.y+35}}
function drawConnections(){layer.setAttribute('viewBox',`0 0 ${Math.max(canvas.clientWidth,1)} ${Math.max(canvas.clientHeight,1)}`);layer.innerHTML='';for(const e of connections){const a=cards.find(c=>String(c.id)===String(e.from)),b=cards.find(c=>String(c.id)===String(e.to));if(!a||!b)continue;const p1=cardCenter(a),p2=cardCenter(b),dx=p2.x-p1.x,dy=p2.y-p1.y,dist=Math.hypot(dx,dy),bend=Math.max(55,Math.min(180,dist*.32));let d;if(Math.abs(dx)>Math.abs(dy))d=`M${p1.x},${p1.y} C${p1.x+Math.sign(dx)*bend},${p1.y-dy*.08} ${p2.x-Math.sign(dx)*bend},${p2.y+dy*.08} ${p2.x},${p2.y}`;else d=`M${p1.x},${p1.y} C${p1.x-dx*.08},${p1.y+Math.sign(dy)*bend} ${p2.x+dx*.08},${p2.y-Math.sign(dy)*bend} ${p2.x},${p2.y}`;const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.classList.add('connection-group');g.dataset.connectionId=String(e.id);if(String(selectedConnection)===String(e.id))g.classList.add('selected');const glow=document.createElementNS('http://www.w3.org/2000/svg','path');glow.setAttribute('d',d);glow.setAttribute('class','connection-glow');glow.dataset.connectionId=String(e.id);const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',d);path.setAttribute('class','connection-line');path.dataset.connectionId=String(e.id);path.addEventListener('click',ev=>{ev.stopPropagation();connectingFrom=null;selectedConnection=String(selectedConnection)===String(e.id)?null:e.id;render()});g.append(glow,path);layer.append(g)}window.dispatchEvent(new CustomEvent('oydin:connections-rendered'))}
function render(){canvas.querySelectorAll('.thought-card').forEach(x=>x.remove());$('#count').textContent=cards.length;$('#connectionCount').textContent=connections.length;$('#emptyState').style.display=cards.length?'none':'grid';if(connectingFrom){$('#flowText').textContent='Aloqa rejimi: endi boshqa fikrni bosing. Esc bilan chiqasiz.';$('#flowAction').textContent='Bekor qilish'}else if(selectedConnection){$('#flowText').textContent='Aloqa tanlangan. Uni istasangiz shu yerdan uzing.';$('#flowAction').textContent='Aloqani uzish'}else{$('#flowText').textContent=cards.length?'Har bir fikrning ichidan davom eting — tartib sizniki.':'Fikr kelgan joyidan boshlang.';$('#flowAction').textContent='+ Fikr'}for(const c of cards){const el=document.createElement('article');el.className=`thought-card ${kindClass(c.type)}${String(connectingFrom)===String(c.id)?' connect-source':''}`;el.dataset.id=c.id;el.tabIndex=0;el.style.left=`${c.x}px`;el.style.top=`${c.y}px`;el.innerHTML=`<div class="card-actions"><button class="add-child" title="Shundan yangi fikr" type="button">＋</button><button class="detail" title="Ichini ochish" type="button">◌</button><button class="edit" title="Tahrirlash" type="button">✎</button><button class="link-card" title="Bog‘lash" type="button">↗</button><button class="delete" title="O‘chirish" type="button">×</button></div><p>${safe(c.text)}</p>`;canvas.append(el);el.querySelector('.add-child').onclick=e=>{e.stopPropagation();openCard(null,c.id)};el.querySelector('.detail').onclick=e=>{e.stopPropagation();openDetail(c.id)};el.querySelector('.edit').onclick=e=>{e.stopPropagation();openCard(c.id)};el.querySelector('.delete').onclick=e=>{e.stopPropagation();deleteCard(c.id)};el.querySelector('.link-card').onclick=e=>{e.stopPropagation();connectingFrom=String(connectingFrom)===String(c.id)?null:String(c.id);selectedConnection=null;render()};el.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;if(connectingFrom&&String(connectingFrom)!==String(c.id)){connect(connectingFrom,c.id);return}selectedConnection=null;drag(el,c,e)})}drawConnections();updateNotes()}
function drag(el,c,e){const sx=e.clientX,sy=e.clientY,ox=c.x,oy=c.y;el.setPointerCapture?.(e.pointerId);const move=ev=>{c.x=ox+(ev.clientX-sx)/(zoom/100);c.y=oy+(ev.clientY-sy)/(zoom/100);el.style.left=c.x+'px';el.style.top=c.y+'px';drawConnections()};const up=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);persist()};el.addEventListener('pointermove',move);el.addEventListener('pointerup',up,{once:true})}
function connect(a,b){if(String(a)===String(b))return;if(!connections.some(e=>(String(e.from)===String(a)&&String(e.to)===String(b))||(String(e.from)===String(b)&&String(e.to)===String(a))))connections.push({id:uid(),from:a,to:b});connectingFrom=null;selectedConnection=null;persist();render()}
function deleteCard(id){cards=cards.filter(c=>String(c.id)!==String(id));connections=connections.filter(e=>String(e.from)!==String(id)&&String(e.to)!==String(id));persist();render()}
function deleteConnection(){if(!selectedConnection)return;connections=connections.filter(e=>String(e.id)!==String(selectedConnection));selectedConnection=null;persist();render()}
function openCard(id=null,parentId=null){editingId=id;childParentId=parentId;const c=id?cards.find(x=>String(x.id)===String(id)):null;$('#dialogKicker').textContent=id?'FIKRNI TAHRIRLASH':parentId?'YANGI DAVOM':'YANGI FIKR';$('#dialogTitle').textContent=id?'Fikrni yangilang':parentId?'Shu fikrdan nimasi davom etadi?':'Hozir nimani o‘ylayapsiz?';$('#thoughtText').value=c?.text||'';selectedType=c?.type||'G‘oya';$$('.type').forEach(x=>x.classList.toggle('selected',x.dataset.type===selectedType));$('#submitCard').innerHTML=id?'Saqlash <span>→</span>':'Makonga qo‘shish <span>→</span>';$('#cardDialog').showModal();setTimeout(()=>$('#thoughtText').focus(),30)}
function closeDialog(){if($('#cardDialog').open)$('#cardDialog').close();editingId=null;childParentId=null}
function submitCard(e){e.preventDefault();const text=$('#thoughtText').value.trim();if(!text)return;if(editingId){const c=cards.find(x=>String(x.id)===String(editingId));if(c){c.text=text;c.type=selectedType}}else{const parent=childParentId?cards.find(x=>String(x.id)===String(childParentId)):null;const i=cards.length;const x=parent?parent.x+290:80+(i%4)*300;const y=parent?parent.y+(i%3-1)*120:120+(Math.floor(i/4)%5)*160;const fresh={id:uid(),text,type:selectedType,x,y,createdAt:new Date().toISOString(),detail:{status:'Ochiq'}};cards.push(fresh);if(parent)connections.push({id:uid(),from:parent.id,to:fresh.id})}persist();closeDialog();render()}
function openDetail(id){detailId=id;const c=cards.find(x=>String(x.id)===String(id));if(!c)return;const d=c.detail||{};$('#detailTitle').textContent=c.text;$('#detailSummary').value=d.summary||'';$('#detailDue').value=d.due||'';$('#detailStatus').value=d.status||'Ochiq';$('#detailNotes').value=d.notes||'';$('#detailDialog').showModal()}
function saveDetail(){const c=cards.find(x=>String(x.id)===String(detailId));if(!c)return;c.detail={summary:$('#detailSummary').value.trim(),due:$('#detailDue').value,status:$('#detailStatus').value,notes:$('#detailNotes').value.trim()};persist();$('#detailDialog').close();render()}
function updateNotes(){const list=$('#notesList');if(!list)return;list.innerHTML=cards.length?cards.map(c=>`<button class="note-row" data-id="${safe(c.id)}"><span>${safe(c.type)}</span><b>${safe(c.text)}</b><small>${c.detail?.due?safe(c.detail.due):'—'}</small></button>`).join(''):'<p class="notes-empty">Hozircha hech qanday fikr yo‘q.</p>';$$('.note-row').forEach(b=>b.onclick=()=>{const c=cards.find(x=>String(x.id)===String(b.dataset.id));if(c){$('#notesDialog').close();openDetail(c.id)}})}
function openMaps(){renderMaps();$('#mapsDialog').showModal()}
function renderMaps(){const list=$('#mapsList');const entries=Object.values(maps).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));list.innerHTML=entries.map(m=>`<div class="saved-map"><button class="saved-map-main" data-open="${safe(m.id)}"><b>${safe(m.title||'Yangi makon')}</b><small>${m.cards?.length||0} fikr · ${new Date(m.updatedAt||Date.now()).toLocaleDateString('uz-UZ')}</small></button><div class="saved-map-actions"><button data-rename="${safe(m.id)}">Nom</button><button data-remove="${safe(m.id)}">O‘chirish</button></div></div>`).join('');$$('[data-open]').forEach(b=>b.onclick=()=>{mapId=b.dataset.open;localStorage.setItem('oydin-active-map',mapId);$('#mapsDialog').close();loadCurrent()});$$('[data-remove]').forEach(b=>b.onclick=()=>{if(Object.keys(maps).length===1)return alert('Oxirgi makonni o‘chirish mumkin emas.');delete maps[b.dataset.remove];localStorage.setItem('oydin-maps',JSON.stringify(maps));if(b.dataset.remove===mapId){mapId=Object.keys(maps)[0];localStorage.setItem('oydin-active-map',mapId);loadCurrent()}renderMaps()});$$('[data-rename]').forEach(b=>b.onclick=()=>{const m=maps[b.dataset.rename],n=prompt('Makon nomi:',m.title);if(n?.trim()){m.title=n.trim();localStorage.setItem('oydin-maps',JSON.stringify(maps));if(b.dataset.rename===mapId)$('#mapTitle').value=m.title;renderMaps()}})}
function newMap(){const id=uid();maps[id]={id,title:'Yangi makon',cards:[],connections:[],space:'paper',updatedAt:new Date().toISOString()};mapId=id;localStorage.setItem('oydin-maps',JSON.stringify(maps));localStorage.setItem('oydin-active-map',id);loadCurrent();$('#mapsDialog').close()}
function fitMap(){if(!cards.length){zoom=100;updateZoom();return}const w=canvas.clientWidth,h=canvas.clientHeight;const roots=cards.filter(c=>!connections.some(e=>String(e.to)===String(c.id))).slice(0,1);const root=roots[0]||cards[0];const levels=new Map([[String(root.id),0]]);const queue=[root];while(queue.length){const c=queue.shift();const level=levels.get(String(c.id));for(const e of connections.filter(x=>String(x.from)===String(c.id))){const n=cards.find(x=>String(x.id)===String(e.to));if(n&&!levels.has(String(n.id))){levels.set(String(n.id),level+1);queue.push(n)}}}const groups={};cards.forEach(c=>{const l=levels.get(String(c.id))??0;(groups[l]??=[]).push(c)});Object.entries(groups).forEach(([level,group])=>{const rowWidth=Math.max(0,(group.length-1)*300);const startX=Math.max(60,(w-rowWidth)/2);const y=Math.max(120,120+Number(level)*150);group.forEach((c,i)=>{c.x=startX+i*300;c.y=y})});const minX=Math.min(...cards.map(c=>c.x)),maxX=Math.max(...cards.map(c=>c.x+250)),minY=Math.min(...cards.map(c=>c.y)),maxY=Math.max(...cards.map(c=>c.y+70));const sx=(w-120)/(maxX-minX||1),sy=(h-180)/(maxY-minY||1);zoom=Math.max(50,Math.min(175,Math.floor(Math.min(sx,sy)*100)));persist();render();updateZoom()}
function updateZoom(){zoom=Math.max(50,Math.min(175,zoom));$('#zoom').textContent=zoom+'%';const px=getComputedStyle(canvas).getPropertyValue('--oydin-pan-x')||'0px',py=getComputedStyle(canvas).getPropertyValue('--oydin-pan-y')||'0px';canvas.style.transform=`translate3d(${px},${py},0) scale(${zoom/100})`;layer.style.transform=`translate3d(${px},${py},0) scale(${zoom/100})`;drawConnections()}
window.OydinMapCamera={setZoom(value){zoom=Math.max(50,Math.min(175,Number(value)*100));updateZoom()},getZoom(){return zoom/100}};
window.OydinMapUI={refresh:loadCurrent,render};
window.addEventListener('oydin:request-render',()=>loadCurrent());
window.addEventListener('oydin:remote-synced',()=>loadCurrent());
function setSpace(name,save=true){const key=spaces[name]?name:'paper';workspace.className=`workspace ${spaces[key].class}`;workspace.dataset.space=key;$('#spaceName').textContent=spaces[key].name;$$('.swatch').forEach(b=>b.classList.toggle('active',b.dataset.space===key));if(save)persist()}
$('#addFirst')?.addEventListener('click',()=>openCard());$('#emptyAdd')?.addEventListener('click',()=>openCard());$('#flowAction')?.addEventListener('click',()=>connectingFrom?(connectingFrom=null,render()):selectedConnection?deleteConnection():openCard());$('#cardForm')?.addEventListener('submit',submitCard);$('#closeCard')?.addEventListener('click',closeDialog);$('#closeDetail')?.addEventListener('click',()=>$('#detailDialog').close());$('#saveDetail')?.addEventListener('click',saveDetail);$$('.type').forEach(b=>b.addEventListener('click',()=>{$$('.type').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedType=b.dataset.type}));$('#openMaps')?.addEventListener('click',openMaps);$('#openMapsTop')?.addEventListener('click',openMaps);$('#closeMaps')?.addEventListener('click',()=>$('#mapsDialog').close());$('#createMap')?.addEventListener('click',newMap);$('#railNotes')?.addEventListener('click',()=>{$('#notesDialog').showModal();updateNotes()});$('#closeNotes')?.addEventListener('click',()=>$('#notesDialog').close());$('#help')?.addEventListener('click',()=>$('#helpDialog').showModal());$('#closeHelp')?.addEventListener('click',()=>$('#helpDialog').close());$('#zoomIn')?.addEventListener('click',()=>{zoom+=10;updateZoom()});$('#zoomOut')?.addEventListener('click',()=>{zoom-=10;updateZoom()});$('#fitMap')?.addEventListener('click',fitMap);$('#newMap')?.addEventListener('click',newMap);$('#saveMap')?.addEventListener('click',persist);$('#mapTitle')?.addEventListener('input',persist);$$('.swatch').forEach(b=>b.addEventListener('click',()=>setSpace(b.dataset.space)));window.addEventListener('resize',drawConnections);document.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&selectedConnection&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();deleteConnection()}if(e.key==='Escape'&&connectingFrom){connectingFrom=null;render()}});loadCurrent();
}

/* Consolidated map surface interaction. */
if(isMapPage){(()=>{
  const pointers=new Map();let gesture=null,panX=0,panY=0,raf=0,lastTap=0;
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  const isMobile=matchMedia('(pointer: coarse)').matches;
  const getZoom=()=>clamp((parseFloat($('#zoom')?.textContent)||100)/100,.5,1.75);
  const point=e=>({x:e.clientX,y:e.clientY});
  const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
  const midpoint=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
  const blankTarget=t=>!!t&&!t.closest('.thought-card,button,input,textarea,select,dialog,.workspace-toolbar,.flow-panel,.space-hint');
  const applyPan=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const z=getZoom();canvas.style.setProperty('--oydin-pan-x',`${panX}px`);canvas.style.setProperty('--oydin-pan-y',`${panY}px`);const t=`translate3d(${panX}px,${panY}px,0) scale(${z})`;canvas.style.transformOrigin='0 0';layer.style.transformOrigin='0 0';canvas.style.transform=t;layer.style.transform=t})};
  const setZoomAt=(next,x,y)=>{const old=getZoom(),z=clamp(next,.5,1.75);if(Math.abs(z-old)<.0001)return;panX=x-(x-panX)*(z/old);panY=y-(y-panY)*(z/old);if(window.OydinMapCamera?.setZoom)window.OydinMapCamera.setZoom(z);else applyPan()};
  const down=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;if(!blankTarget(e.target))return;pointers.set(e.pointerId,point(e));if(pointers.size===2){const [a,b]=[...pointers.values()];gesture={type:'pinch',d:Math.max(1,distance(a,b)),m:midpoint(a,b),s:getZoom(),px:panX,py:panY};e.preventDefault();return}const p=point(e);gesture={type:'pending',start:p,last:p}};
  const move=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,point(e));if(pointers.size>=2){const [a,b]=[...pointers.values()];if(!gesture||gesture.type!=='pinch')gesture={type:'pinch',d:Math.max(1,distance(a,b)),m:midpoint(a,b),s:getZoom(),px:panX,py:panY};const d=Math.max(1,distance(a,b)),m=midpoint(a,b),z=clamp(gesture.s*d/gesture.d,.5,1.75);panX=m.x-(gesture.m.x-gesture.px)*(z/gesture.s);panY=m.y-(gesture.m.y-gesture.py)*(z/gesture.s);canvas.style.setProperty('--oydin-pan-x',`${panX}px`);canvas.style.setProperty('--oydin-pan-y',`${panY}px`);if(window.OydinMapCamera?.setZoom)window.OydinMapCamera.setZoom(z);else applyPan();e.preventDefault();return}if(!gesture||gesture.type==='pinch')return;const p=point(e),dx=p.x-gesture.start.x,dy=p.y-gesture.start.y;if(gesture.type==='pending'&&Math.hypot(dx,dy)>6)gesture.type=isMobile&&Math.abs(dy)>Math.abs(dx)*1.12?'page-scroll':'pan';if(gesture.type==='pan'){panX+=p.x-gesture.last.x;panY+=p.y-gesture.last.y;gesture.last=p;applyPan();e.preventDefault()}};
  const up=e=>{pointers.delete(e.pointerId);if(!pointers.size){gesture=null;return}if(pointers.size===1&&gesture?.type==='pinch'){const p=[...pointers.values()][0];gesture={type:'pending',start:p,last:p}}};
  workspace.addEventListener('pointerdown',down,{passive:false});workspace.addEventListener('pointermove',move,{passive:false});workspace.addEventListener('pointerup',up,{passive:true});workspace.addEventListener('pointercancel',up,{passive:true});
  workspace.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();const r=workspace.getBoundingClientRect();setZoomAt(getZoom()*Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top)}},{passive:false});
  workspace.addEventListener('click',e=>{const card=e.target.closest('.thought-card');if(!card||e.target.closest('button'))return;if(matchMedia('(pointer: coarse)').matches){workspace.querySelectorAll('.thought-card.actions-open').forEach(x=>{if(x!==card)x.classList.remove('actions-open')});card.classList.toggle('actions-open')}});
  workspace.addEventListener('pointerup',e=>{if(e.pointerType!=='touch'||!blankTarget(e.target))return;const now=Date.now();if(now-lastTap<320)$('#emptyAdd')?.click();lastTap=now},{passive:true});
  document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#addFirst')?.click()}if(e.key.toLowerCase()==='n'){e.preventDefault();$('#addFirst')?.click()}if(e.key==='Escape')workspace.querySelectorAll('.thought-card.actions-open').forEach(x=>x.classList.remove('actions-open'))});
  applyPan();
})();}

/* Consolidated product layer: history, search and export. */
if(isMapPage||document.querySelector('#ideas'))(()=>{
  const MAP=isMapPage,OQIM=!!document.querySelector('#ideas');
  if(MAP){
    const HKEY='oydin-history-v1',MAX=30;let lastMaps=localStorage.getItem('oydin-maps'),recording=true;
    const recordHistory=value=>{if(!recording||value===lastMaps)return;try{if(lastMaps){const history=JSON.parse(localStorage.getItem(HKEY)||'[]');history.push({maps:lastMaps,active:localStorage.getItem('oydin-active-map')});localStorage.setItem(HKEY,JSON.stringify(history.slice(-MAX)))}}catch{}lastMaps=value};
    window.addEventListener('oydin:data-changed',e=>{if(e.detail?.key==='oydin-maps')recordHistory(e.detail.value??localStorage.getItem('oydin-maps'))});
    const historyBack=()=>{try{const history=JSON.parse(localStorage.getItem(HKEY)||'[]'),item=history.pop();if(!item)return;recording=false;localStorage.setItem(HKEY,JSON.stringify(history));localStorage.setItem('oydin-maps',item.maps);if(item.active)localStorage.setItem('oydin-active-map',item.active);recording=true;lastMaps=item.maps;window.dispatchEvent(new CustomEvent('oydin:history-restored',{detail:item}));window.dispatchEvent(new CustomEvent('oydin:data-changed',{detail:{key:'oydin-maps',value:item.maps,operation:'restore'}}))}catch{}};
    const focusCard=el=>{el?.classList.add('search-hit');el?.scrollIntoView?.({block:'center',inline:'center',behavior:'smooth'});setTimeout(()=>el?.classList.remove('search-hit'),1200)};
    const openSearch=()=>{let d=$('#mapSearchDialog');if(!d){d=document.createElement('dialog');d.id='mapSearchDialog';d.innerHTML='<div class="product-dialog"><button class="dialog-close" data-close>×</button><p class="kicker">MAKON ICHIDA</p><h2>Fikrni toping</h2><input id="mapSearchInput" autocomplete="off" placeholder="Fikrni qidiring…"><div id="mapSearchResults"></div></div>';document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close()}const input=d.querySelector('#mapSearchInput'),results=d.querySelector('#mapSearchResults');const run=()=>{const q=input.value.trim().toLowerCase();results.innerHTML='';document.querySelectorAll('.thought-card').forEach(c=>{const text=c.querySelector('p')?.textContent||'';if(!q||text.toLowerCase().includes(q)){const b=document.createElement('button');b.className='search-result';b.textContent=text;b.onclick=()=>{d.close();focusCard(c)};results.append(b)}});if(!results.children.length)results.innerHTML='<p class="product-empty">Mos fikr topilmadi.</p>'};input.oninput=run;d.showModal();setTimeout(()=>{input.focus();run()},30)};
    const exportMap=()=>{try{const all=JSON.parse(localStorage.getItem('oydin-maps')||'{}'),id=localStorage.getItem('oydin-active-map'),data=all[id];if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(data.title||'oydin-makon').replace(/[^\p{L}\p{N}\-_ ]/gu,'').trim()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}catch{}};
    const addTools=()=>{const cluster=document.querySelector('.workspace-toolbar .tool-cluster');if(!cluster||$('#oydinProductTools'))return;const wrap=document.createElement('div');wrap.id='oydinProductTools';wrap.className='tool-cluster product-tools';wrap.innerHTML='<button id="historyUndo" title="Bekor qilish · Ctrl/Cmd+Z" aria-label="Bekor qilish">↶</button><button id="focusSearch" title="Makon ichidan qidirish · /" aria-label="Qidirish">⌕</button><button id="exportSpace" title="Makonni eksport qilish" aria-label="Eksport">↓</button>';cluster.parentElement?.insertBefore(wrap,cluster.parentElement.firstChild);$('#historyUndo').onclick=historyBack;$('#focusSearch').onclick=openSearch;$('#exportSpace').onclick=exportMap};
    window.addEventListener('oydin:history-restored',()=>window.dispatchEvent(new CustomEvent('oydin:request-render')));document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();historyBack()}if(e.key==='/'){e.preventDefault();openSearch()}});addTools();
  }
  if(OQIM){const list=$('#ideas');if(list){const addSearch=()=>{if($('#oqimSearch'))return;const box=document.createElement('div');box.className='oqim-search';box.innerHTML='<span>⌕</span><input id="oqimSearch" placeholder="Oqimdan qidiring…" aria-label="Oqimdan qidiring">';list.parentElement?.insertBefore(box,list);const search=box.querySelector('input');search.oninput=()=>{const q=search.value.trim().toLowerCase();list.querySelectorAll('.idea-row').forEach(row=>{row.style.display=(!q||(row.querySelector('.idea-text')?.textContent||'').toLowerCase().includes(q))?'grid':'none'})};document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,button'))return;if(e.key==='/'){e.preventDefault();search.focus()}})};addSearch()}}
})();

/* Consolidated connection anchors. Lines terminate at the card boundary, not through readable text. */
if(isMapPage){(()=>{
  const svg=layer;
  const center=el=>({x:(parseFloat(el.style.left)||0)+el.offsetWidth/2,y:(parseFloat(el.style.top)||0)+el.offsetHeight/2});
  const anchor=(el,target,gap=8)=>{const w=el.offsetWidth,h=el.offsetHeight,c=center(el),dx=target.x-c.x,dy=target.y-c.y,sx=Math.abs(dx)/(w/2||1),sy=Math.abs(dy)/(h/2||1),k=1/Math.max(sx,sy,1e-6),px=c.x+dx*k,py=c.y+dy*k,len=Math.hypot(dx,dy)||1;return{x:px+dx/len*gap,y:py+dy/len*gap}};
  const redraw=()=>{const cardsNow=[...canvas.querySelectorAll('.thought-card')],groups=[...svg.querySelectorAll('.connection-group')];if(!cardsNow.length||!groups.length)return;const centers=cardsNow.map(el=>({el,...center(el)}));groups.forEach(group=>{const path=group.querySelector('.connection-line'),glow=group.querySelector('.connection-glow');if(!path)return;const nums=(path.getAttribute('d')||'').match(/-?\d*\.?\d+(?:e[-+]?\d+)?/gi)?.map(Number)||[];if(nums.length<8)return;const oldA={x:nums[0],y:nums[1]},oldB={x:nums[6],y:nums[7]};const a=centers.reduce((best,p)=>!best||Math.hypot(p.x-oldA.x,p.y-oldA.y)<Math.hypot(best.x-oldA.x,best.y-oldA.y)?p:best,null),b=centers.reduce((best,p)=>!best||Math.hypot(p.x-oldB.x,p.y-oldB.y)<Math.hypot(best.x-oldB.x,best.y-oldB.y)?p:best,null);if(!a||!b||a===b)return;const p1=anchor(a.el,{x:b.x,y:b.y}),p2=anchor(b.el,{x:a.x,y:a.y}),dx=p2.x-p1.x,dy=p2.y-p1.y,dist=Math.hypot(dx,dy),bend=Math.max(55,Math.min(180,dist*.32));const d=Math.abs(dx)>Math.abs(dy)?`M${p1.x},${p1.y} C${p1.x+Math.sign(dx)*bend},${p1.y-dy*.08} ${p2.x-Math.sign(dx)*bend},${p2.y+dy*.08} ${p2.x},${p2.y}`:`M${p1.x},${p1.y} C${p1.x-dx*.08},${p1.y+Math.sign(dy)*bend} ${p2.x+dx*.08},${p2.y-Math.sign(dy)*bend} ${p2.x},${p2.y}`;path.setAttribute('d',d);if(glow)glow.setAttribute('d',d)});window.dispatchEvent(new CustomEvent('oydin:connections-anchored'))};
  let queued=false;const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;redraw()})};window.addEventListener('oydin:connections-rendered',schedule);window.addEventListener('resize',schedule);schedule();
})();}

/* Consolidated thinking layer. */
if(isMapPage){(()=>{
  const REL_KEY='oydin-connection-relations-v1',relations=(()=>{try{return JSON.parse(localStorage.getItem(REL_KEY)||'{}')}catch{return{}}})();
  const relationTypes=[['davomi','Davomi'],['sabab','Sabab'],['natija','Natija'],['qarshi','Qarama-qarshi'],['izoh','Izoh']];let focused=null,relationPanel=null;
  const cardsNow=()=>[...canvas.querySelectorAll('.thought-card')],idOf=el=>String(el?.dataset?.id||'');
  const getStoredConnections=()=>{try{const mapsNow=JSON.parse(localStorage.getItem('oydin-maps')||'{}'),id=localStorage.getItem('oydin-active-map');return mapsNow[id]?.connections||[]}catch{return[]}};
  const neighbors=id=>{const out=new Set([String(id)]);getStoredConnections().forEach(e=>{if(String(e.from)===String(id))out.add(String(e.to));if(String(e.to)===String(id))out.add(String(e.from))});return out};
  const clearFocus=()=>{focused=null;workspace.classList.remove('thinking-focus');cardsNow().forEach(c=>c.classList.remove('is-dimmed','is-focused'));$('#exitThinkingFocus')?.remove()};
  const focusCard=card=>{if(!card)return;focused=idOf(card);const allowed=neighbors(focused);workspace.classList.add('thinking-focus');cardsNow().forEach(c=>{const on=allowed.has(idOf(c));c.classList.toggle('is-focused',idOf(c)===focused);c.classList.toggle('is-dimmed',!on)});let button=$('#exitThinkingFocus');if(!button){button=document.createElement('button');button.id='exitThinkingFocus';button.type='button';button.innerHTML='<span>×</span> Fikr ko‘rishdan chiqish';workspace.appendChild(button);button.onclick=clearFocus}};
  const ensureCardTools=()=>cardsNow().forEach(card=>{if(card.querySelector('.thinking-focus-action'))return;const actions=card.querySelector('.card-actions');if(!actions)return;const b=document.createElement('button');b.type='button';b.className='thinking-focus-action';b.title='Shu fikr atrofini ko‘rish';b.setAttribute('aria-label',b.title);b.textContent='◎';b.onclick=e=>{e.stopPropagation();focusCard(card)};actions.insertBefore(b,actions.firstChild)});
  const relationName=id=>relations[id]?.label||'',connectionId=group=>String(group?.dataset?.connectionId||group?.querySelector('.connection-line')?.dataset?.connectionId||'');
  const paintRelationLabels=()=>{layer.querySelectorAll('.thinking-relation-label').forEach(x=>x.remove());layer.querySelectorAll('.connection-line').forEach(path=>{const group=path.closest('.connection-group'),id=connectionId(group)||String(path.dataset.connectionId||''),label=relationName(id);if(!group||!id||!label)return;try{const p=path.getPointAtLength(path.getTotalLength()/2),text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x',p.x);text.setAttribute('y',p.y-8);text.setAttribute('text-anchor','middle');text.setAttribute('class','thinking-relation-label');text.textContent=label;text.style.pointerEvents='none';layer.appendChild(text)}catch{}})};
  const selectedConnectionId=()=>{const selected=layer.querySelector('.connection-group.selected');return selected?connectionId(selected)||null:null};
  const closePanel=()=>{relationPanel?.remove();relationPanel=null};
  const openRelationPanel=id=>{if(!id)return;closePanel();relationPanel=document.createElement('div');relationPanel.id='relationPanel';relationPanel.innerHTML=`<div class="relation-head"><span>Aloqa turi</span><button type="button" aria-label="Yopish">×</button></div><div class="relation-options">${relationTypes.map(([k,l])=>`<button type="button" data-rel="${k}" class="${relations[id]?.type===k?'selected':''}">${l}</button>`).join('')}</div><p>Bu yorliq fikrlar orasidagi munosabatni eslab qoladi.</p>`;workspace.appendChild(relationPanel);relationPanel.querySelector('.relation-head button').onclick=closePanel;relationPanel.querySelectorAll('[data-rel]').forEach(b=>b.onclick=()=>{const type=b.dataset.rel;relations[id]={type,label:relationTypes.find(x=>x[0]===type)?.[1]||type};localStorage.setItem(REL_KEY,JSON.stringify(relations));relationPanel.querySelectorAll('[data-rel]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');paintRelationLabels()})};
  const scan=()=>{ensureCardTools();const selected=selectedConnectionId();if(selected)openRelationPanel(selected);else closePanel();paintRelationLabels();if(focused){const allowed=neighbors(focused);cardsNow().forEach(c=>{const on=allowed.has(idOf(c));c.classList.toggle('is-dimmed',!on);c.classList.toggle('is-focused',idOf(c)===focused)})}};
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){closePanel();if(focused)clearFocus()}});document.addEventListener('dblclick',e=>{const card=e.target.closest?.('.thought-card');if(card&&!e.target.closest('button'))focusCard(card)});window.addEventListener('oydin:connections-rendered',()=>requestAnimationFrame(scan));window.addEventListener('oydin:connections-anchored',()=>requestAnimationFrame(scan));new MutationObserver(()=>requestAnimationFrame(scan)).observe(canvas,{childList:true,subtree:true});requestAnimationFrame(scan);
})();}
