const $=s=>document.querySelector(s);
const messages=$('#chatMessages');
const KEY='oydin-core-v2';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{thoughts:[],history:[],title:'Bugungi fikrlar',theme:'light'};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const safe=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state));$('#saveStatus').textContent='Saqlangan'}
function classify(text){const t=text.toLowerCase();let type='thought';if(/(g‘oya|g'oya|idea|startup|loyiha|fikr)/.test(t))type='idea';if(/(kerak|qilishim|vazifa|ertaga|bugun)/.test(t))type='task';if(/(tanlash|qaror|qaysi|ikkilan|yoki)/.test(t))type='decision';if(/(maqsad|xohlayman|istayman|reja)/.test(t))type='goal';if(/(nima uchun|nega|savol|bilmayman)/.test(t))type='question';return type}
function label(type){return {thought:'FIKR',idea:'G‘OYA',task:'VAZIFA',decision:'QAROR',goal:'MAQSAD',question:'SAVOL'}[type]||'FIKR'}
function addMessage(role,text){const w=messages.querySelector('.welcome');if(w)w.remove();const e=document.createElement('div');e.className=`chat-message ${role}`;e.innerHTML=role==='ai'?`<div class="avatar">o</div><div class="bubble">${safe(text)}</div>`:`<div class="bubble">${safe(text)}</div>`;messages.append(e);messages.scrollTop=messages.scrollHeight}
function addThought(text){const thought={id:uid(),text,type:classify(text),createdAt:new Date().toISOString(),pinned:false};state.thoughts.unshift(thought);save();return thought}
function localReply(t){const type=classify(t);if(type==='idea')return 'Saqladim. G‘oya yo‘qolmaydi. Xohlasangiz keyin uni alohida rivojlantirasiz.';if(type==='task')return 'Saqladim. Bu fikr keyin vazifa sifatida ko‘rinadi.';if(type==='decision')return 'Saqladim. Bu fikr keyin qaror sifatida qayta ko‘rib chiqishga tayyor.';if(type==='goal')return 'Saqladim. Maqsad sifatida belgilab qo‘ydim.';return state.thoughts.length===1?'Fikringizni saqladim. Hozircha uni o‘zgartirmayman — keyin boshqa fikrlaringiz bilan bog‘lash mumkin.':'Saqladim. Muhimi, fikr yo‘qolmaydi. Oydin sizni ortiqcha savollar bilan bo‘lmaydi.'}
function send(text){const thought=addThought(text);const reply=localReply(text);state.history.push({role:'user',text,thoughtId:thought.id},{role:'assistant',text:reply});addMessage('user',text);addMessage('ai',reply);save()}
function renderThoughts(){const c=$('#canvas');c.querySelectorAll('.thought-card').forEach(x=>x.remove());$('#count').textContent=`${state.thoughts.length} ta fikr`;$('#emptyState').style.display=state.thoughts.length?'none':'block';state.thoughts.slice().reverse().forEach((n,i)=>{const e=document.createElement('article');e.className='thought-card idea';e.style.left=80+(i%3)*270+'px';e.style.top=90+Math.floor(i/3)*165+'px';e.innerHTML=`<button class="pin" data-pin="${n.id}" title="Muhim">${n.pinned?'★':'☆'}</button><span class="card-type">${label(n.type)}</span><p>${safe(n.text)}</p><small>${new Date(n.createdAt).toLocaleDateString('uz-UZ')}</small>`;c.append(e)});c.querySelectorAll('[data-pin]').forEach(b=>b.onclick=()=>{const n=state.thoughts.find(x=>x.id===b.dataset.pin);n.pinned=!n.pinned;save();renderThoughts()})}
function showFlow(){document.querySelector('.chat-shell').classList.add('hidden');document.querySelector('.intro').classList.add('hidden');$('#flowWorkspace').classList.remove('hidden');renderThoughts()}
$('#chatForm').onsubmit=e=>{e.preventDefault();const i=$('#chatInput'),t=i.value.trim();if(t){i.value='';send(t)}};
document.querySelectorAll('[data-starter]').forEach(b=>b.onclick=()=>send(b.dataset.starter));
$('#startChat').onclick=()=>$('#chatInput').focus();$('#showFlow').onclick=showFlow;
$('#newMap').onclick=()=>{if(confirm('Yangi fikrlar sahifasi boshlansinmi?')){state={thoughts:[],history:[],title:'Bugungi fikrlar',theme:state.theme};messages.innerHTML='<div class="welcome"><div class="welcome-mark">o</div><h2>Men Oydinman.</h2><p>Bugun nimani o‘ylayapsiz? Fikringizni qanday bo‘lsa, shunday yozing.</p></div>';save()}};
$('#themeToggle').onclick=()=>{document.body.classList.toggle('night');state.theme=document.body.classList.contains('night')?'night':'light';save()};if(state.theme==='night')document.body.classList.add('night');
$('#mapTitle').value=state.title;$('#mapTitle').oninput=()=>{state.title=$('#mapTitle').value;save()};
$('#openMinute').onclick=$('#openMinuteHero').onclick=()=>$('#minuteDialog').showModal();$('#closeMinute').onclick=()=>$('#minuteDialog').close();$('#help').onclick=()=>$('#helpDialog').showModal();$('#closeHelp').onclick=()=>$('#helpDialog').close();
state.history.forEach(x=>addMessage(x.role==='assistant'?'ai':'user',x.text));if(state.history.length)messages.querySelector('.welcome')?.remove();save();