const input=document.querySelector('#ideaInput');
const save=document.querySelector('#saveIdea');
const list=document.querySelector('#ideas');
const count=document.querySelector('#ideaCount');
const key='oydin-oqim';
const load=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let ideas=load();
function persist(){localStorage.setItem(key,JSON.stringify(ideas));}
function updateCount(){if(count)count.textContent=`${input?.value.length||0} / 1000`;}
function add(){const text=input.value.trim();if(!text)return;ideas.unshift({id:uid(),text,createdAt:new Date().toISOString()});input.value='';updateCount();persist();render();input.focus();}
function moveToMakon(id){const idea=ideas.find(x=>x.id===id);if(!idea)return;let maps;try{maps=JSON.parse(localStorage.getItem('oydin-maps')||'{}')}catch{maps={}};let mapId=localStorage.getItem('oydin-active-map')||'map-default';if(!maps[mapId])maps[mapId]={id:mapId,title:'Yangi makon',cards:[],connections:[],space:'paper',updatedAt:new Date().toISOString()};const map=maps[mapId];const i=map.cards.length;map.cards.push({id:uid(),text:idea.text,type:'G‘oya',x:80+(i%4)*300,y:120+(Math.floor(i/4)%5)*160,createdAt:new Date().toISOString(),detail:{status:'Ochiq'}});map.updatedAt=new Date().toISOString();localStorage.setItem('oydin-maps',JSON.stringify(maps));localStorage.setItem('oydin-active-map',mapId);ideas=ideas.filter(x=>x.id!==id);persist();render();}
function edit(id){const idea=ideas.find(x=>x.id===id);if(!idea)return;renderEditing(id);}
function saveEdit(id){const idea=ideas.find(x=>x.id===id),el=document.querySelector(`[data-editor="${id}"]`);if(!idea||!el)return;const text=el.value.trim();if(text){idea.text=text;idea.updatedAt=new Date().toISOString();persist();render();}}
function remove(id){ideas=ideas.filter(x=>x.id!==id);persist();render();}
function renderEditing(id){render(id);const el=document.querySelector(`[data-editor="${id}"]`);el?.focus();el?.setSelectionRange(el.value.length,el.value.length);}
function render(editingId=null){if(!list)return;list.innerHTML=ideas.length?ideas.map(x=>editingId===x.id?`<article class="idea-row is-editing"><div><textarea class="idea-edit" data-editor="${x.id}" maxlength="1000">${esc(x.text)}</textarea><button class="primary-button compact idea-save" data-save="${x.id}">Saqlash <span>→</span></button></div><div class="idea-actions"><button class="icon-button" data-cancel="${x.id}" aria-label="Bekor qilish">×</button></div></article>`: `<article class="idea-row"><div><p class="idea-text">${esc(x.text)}</p><small class="idea-date">${new Date(x.createdAt).toLocaleString('uz-UZ')}</small></div><div class="idea-actions"><button class="soft-button" data-move="${x.id}">Makon'ga</button><button class="icon-button" data-edit="${x.id}" aria-label="Tahrirlash">✎</button><button class="icon-button" data-delete="${x.id}" aria-label="O‘chirish">×</button></div></article>`).join(''):'<div class="oqim-empty">Hozircha bu yer bo‘sh.</div>';
list.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveToMakon(b.dataset.move));list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));list.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveEdit(b.dataset.save));list.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>render());
}
save?.addEventListener('click',add);input?.addEventListener('input',updateCount);input?.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();add()}if(e.key==='Enter'&&!e.shiftKey&&!e.ctrlKey&&!e.metaKey){e.preventDefault();add()}});document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,button'))return;if(e.key.toLowerCase()==='n'){e.preventDefault();input?.focus()}});updateCount();render();